// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Routes = require("./routes.bs.js");
var Express = require("express");

var app = Express();

app.use(Express.json);

var extended = {
  extended: true
};

app.use(Express.urlencoded(extended));

app.get("/", Routes.healthCheck);

app.post("/compile/", Routes.postCompile);

function start(param) {
  return app.listen(3000, (function (param) {
                console.log("Listening at http://localhost:" + String(3000) + "");
              }));
}

var port = 3000;

exports.app = app;
exports.port = port;
exports.extended = extended;
exports.start = start;
/* app Not a pure module */
