// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Express = require("express");

var app = Express();

function healthCheck(req, res, next) {
  console.log("GET /");
  res.setHeader("Content-Type", "text/plain");
  res.write("Ok");
  return res.end(undefined);
}

function postCompile(req, res, next) {
  console.log("POST /compile/");
  res.setHeader("Content-Type", "text/plain");
  res.write("Ok");
  return res.end(undefined);
}

app.get("/", healthCheck);

app.post("/compile/", postCompile);

function start(param) {
  return app.listen(3000, (function (param) {
                console.log("Listening at http://localhost:" + String(3000) + "");
              }));
}

var port = 3000;

exports.app = app;
exports.port = port;
exports.healthCheck = healthCheck;
exports.postCompile = postCompile;
exports.start = start;
/* app Not a pure module */
