// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function healthCheck(req, res, next) {
  console.log("GET /");
  res.setHeader("Content-Type", "text/plain");
  res.write("Ok");
  return res.end(undefined);
}

function postCompile(req, res, next) {
  console.log("POST /compile/");
  res.setHeader("Content-Type", "text/plain");
  res.write("Ok");
  return res.end(undefined);
}

exports.healthCheck = healthCheck;
exports.postCompile = postCompile;
/* No side effect */
