// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("@enspirit/dem-core-rescript/src/app.bs.js");

function healthCheck(req, res, next) {
  console.log("GET /");
  res.setHeader("Content-Type", "text/plain");
  res.write("Ok");
  return res.end(undefined);
}

function postCompile(req, res, next) {
  console.log("POST /compile/");
  App.compile(undefined, undefined, undefined, undefined, undefined);
  res.setHeader("Content-Type", "text/plain");
  res.write("Ok");
  return res.end(undefined);
}

exports.healthCheck = healthCheck;
exports.postCompile = postCompile;
/* App Not a pure module */
